# The base image to start from
FROM node:16.13.0-buster

# Setup working directory for the app
WORKDIR /app

# Copy the package and package-lock files
COPY package*.json ./

# Install node modules
RUN npm install
  # Also install development dependencies

# Copy the application files
COPY . .

# Launch the application
CMD npm run dev