{
 "title": "Crodeon",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Bemalingscase",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n    bucket: \"crodeon\",\r\n    tag: \"name\",\r\n    measurement: \"crodeon\",\r\n)"
   },
   {
    "name": "sensor_id",
    "label": "SensorIDs",
    "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volumetric_water_content_soil_moisture_volumetric\")\r\n  |> distinct(column: \"sensor_id\")\r\n  |> keep(columns: [\"sensor_id\"])\r\n  |> map(fn: (r) => ({sensor: r.sensor_id}))"
   }
  ]
 },
 "panels": [
  {
   "title": "Reporter Internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power Supply (Reporter Internal)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 5, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"power_supply_reporter_internal\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Atmospheric Pressure (Reporter Internal)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"atmos_pressure_reporter_internal\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Evolution Power Supply (Reporter Internal)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"power_supply_reporter_internal\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Evolution Atmospheric Pressure (Reporter Internal)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"atmos_pressure_reporter_internal\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Weather Station",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature (Weather Station)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature_weather_station\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Rain (Weather Station)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "L/day" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rain_weather_station\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Dew Point (Weather Station)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dew_point_weather_station\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Humidity (Weather Station)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dew_point_weather_station\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Wet Bulb (Weather Station)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"wet_bulb_weather_station\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Wind Direction (Weather Station)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "degree" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"wind_direction_weather_station\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Max Wind Speed (Weather Station)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"max_wind_speed_weather_station\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Average Wind Speed (Weather Station)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "velocityms" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"average_wind_speed_weather_station\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Soil Moisture (Volumetric) - $sensor_id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "repeat": "sensor_id",
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature Soil (Volumetric)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature_soil_moisture_volumetric\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"${sensor_id}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Soil Water Content (Volumetric)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"volumetric_water_content_soil_moisture_volumetric\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> filter(fn: (r) => r[\"sensor_id\"] == \"${sensor_id}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Soil Moisture (Tensiometers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature Soil (Tensiometer)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature_soil_moisture_tension\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Water Tension 1 (Tensiometer)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"water_tension_1_soil_moisture_tension\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Water Tension 2 (Tensiometer)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"water_tension_2_soil_moisture_tension\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Water Tension 3 (Tensiometer)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
     "targets": [
      {
       "query": "from(bucket: \"crodeon\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"crodeon\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"water_tension_3_soil_moisture_tension\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"${name}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  }
 ]
}