{
 "title": "Dragino Divers",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DeviceId",
    "label": "Device ID",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n    bucket: \"dust\",\r\n    tag: \"devId\",\r\n    measurement: \"dragino-diver\",\r\n)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sensor Depth",
   "type": "stat",
   "description": "Note: depth should always be increased with 20mm to account for sensor offset.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dragino-diver\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"waterLevel\")\r\n  |> filter(fn: (r) => r[\"devId\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dragino-diver\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"battery\")\r\n  |> filter(fn: (r) => r[\"devId\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Sensor Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dragino-diver\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\r\n  |> filter(fn: (r) => r[\"devId\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\", \"devId\", \"hardwareSerial\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Sensor Depth Evolution",
   "type": "timeseries",
   "description": "Note: depth should always be increased with 20mm to account for sensor offset.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cm" } },
   "targets": [
    {
     "alias": "-60cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dragino-diver\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"waterLevel\")\r\n  |> filter(fn: (r) => r[\"devId\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    },
    {
     "alias": "-45cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "select": [
      [
       { "params": [ "moistureLevel_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    },
    {
     "alias": "-20cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "select": [
      [
       { "params": [ "moistureLevel_3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    },
    {
     "alias": "-10cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage Evolution",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dragino-diver\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"battery\")\r\n  |> filter(fn: (r) => r[\"devId\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "LoRaWAN - RSSI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Number of gateways",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dragino-diver\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi\")\r\n  |> filter(fn: (r) => r[\"devId\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "gateways" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "LoRaWAN - # Gateways",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Number of gateways",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dragino-diver\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gateways\")\r\n  |> filter(fn: (r) => r[\"devId\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "gateways" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  }
 ]
}