{
 "title": "Dust SapFlow Sensors",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DeviceId",
    "label": "Device ID",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurementTagValues(\r\n    bucket: \"dust\",\r\n    tag: \"device_id\",\r\n    measurement: \"sapflow-sensor\",\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Alpha Inner",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alphaInner\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Alpha Outer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alphaOuter\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Beta Inner",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"betaInner\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Beta Outer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"betaOuter\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Sap Flow",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "l/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sapFlow\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"battery\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Sap Flow Evolution",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "-60cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sapFlow\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    },
    {
     "alias": "-45cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "select": [
      [
       { "params": [ "moistureLevel_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    },
    {
     "alias": "-20cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "select": [
      [
       { "params": [ "moistureLevel_3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    },
    {
     "alias": "-10cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Daily Sap Flow (Sum)",
   "type": "barchart",
   "description": "Is capped by time range",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "-60cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sapFlow\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> sort(columns: [\"_time\"], desc: false)\r\n  |> unique(column: \"_time\")\r\n  |> aggregateWindow(every: 1d, fn: (tables=<-, column) => tables\r\n    |> integral(unit: 1h), createEmpty: false)",
     "select": [
      [
       { "params": [ "moistureLevel_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    },
    {
     "alias": "-45cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "select": [
      [
       { "params": [ "moistureLevel_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    },
    {
     "alias": "-20cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "select": [
      [
       { "params": [ "moistureLevel_3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    },
    {
     "alias": "-10cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Alpha - Beta Evolution",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "-60cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alphaInner\" or r[\"_field\"] == \"alphaOuter\" or r[\"_field\"] == \"betaInner\" or r[\"_field\"] == \"betaOuter\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    },
    {
     "alias": "-45cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "select": [
      [
       { "params": [ "moistureLevel_2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    },
    {
     "alias": "-20cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "select": [
      [
       { "params": [ "moistureLevel_3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    },
    {
     "alias": "-10cm",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Outer Temperature Evolution",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "RSSI",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatureOuter\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    },
    {
     "alias": "SNR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "LoRaWAN - RSSI",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Number of gateways",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rssi\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "gateways" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "LoRaWAN - # Gateways",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Number of gateways",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"gateways\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "gateways" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Heat Velocity Inner",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cm/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"heatVelocityInner\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Heat Velocity Inner",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cm/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"heatVelocityInner\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage Evolution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"battery\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Tmax Inner",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tmaxInner\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Tmax Outer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tmaxOuter\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Minimum Voltage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"minVoltage\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Maximum Voltage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"maxVoltage\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Tmax Inner",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upstreamTmaxInner\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  },
  {
   "title": "Upstream Tmax Outer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tph",
     "query": "from(bucket: \"dust\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sapflow-sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upstreamTmaxOuter\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"${DeviceId}\")\r\n  |> drop(columns: [\"codingRate\", \"diagnostic\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "moistureLevel_4" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "devId", "operator": "=~", "value": "/^$DeviceId$/" }
     ]
    }
   ]
  }
 ]
}